/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/history/': RouteRecordInfo<
      '/history/',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/libraries/': RouteRecordInfo<
      '/libraries/',
      '/libraries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/libraries/[name]': RouteRecordInfo<
      '/libraries/[name]',
      '/libraries/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/quality/': RouteRecordInfo<
      '/quality/',
      '/quality',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/repositories/': RouteRecordInfo<
      '/repositories/',
      '/repositories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/repositories/[name]': RouteRecordInfo<
      '/repositories/[name]',
      '/repositories/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/session/': RouteRecordInfo<
      '/session/',
      '/session',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspaces/': RouteRecordInfo<
      '/workspaces/',
      '/workspaces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspaces/[name]': RouteRecordInfo<
      '/workspaces/[name]',
      '/workspaces/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/history/index.vue': {
      routes:
        | '/history/'
      views:
        | never
    }
    'src/pages/libraries/index.vue': {
      routes:
        | '/libraries/'
      views:
        | never
    }
    'src/pages/libraries/[name].vue': {
      routes:
        | '/libraries/[name]'
      views:
        | never
    }
    'src/pages/quality/index.vue': {
      routes:
        | '/quality/'
      views:
        | never
    }
    'src/pages/repositories/index.vue': {
      routes:
        | '/repositories/'
      views:
        | never
    }
    'src/pages/repositories/[name].vue': {
      routes:
        | '/repositories/[name]'
      views:
        | never
    }
    'src/pages/search/index.vue': {
      routes:
        | '/search/'
      views:
        | never
    }
    'src/pages/session/index.vue': {
      routes:
        | '/session/'
      views:
        | never
    }
    'src/pages/workspaces/index.vue': {
      routes:
        | '/workspaces/'
      views:
        | never
    }
    'src/pages/workspaces/[name].vue': {
      routes:
        | '/workspaces/[name]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
