"""Tool framework - base classes, param traits, and auto-discovery."""

from sylvan.tools.base.hints import HintBuilder
from sylvan.tools.base.meta import ToolMeta, get_meta, reset_meta, set_meta
from sylvan.tools.base.params import (
    HasContextLines,
    HasDepth,
    HasDirection,
    HasDocPath,
    HasFileFilter,
    HasFilePath,
    HasFilePaths,
    HasKindFilter,
    HasLanguageFilter,
    HasMaxDepth,
    HasOptionalFilePath,
    HasOptionalProjectPath,
    HasOptionalRepo,
    HasOptionalSymbol,
    HasPagination,
    HasProjectPath,
    HasQuery,
    HasRepo,
    HasSectionId,
    HasSectionIds,
    HasSymbol,
    HasSymbolIds,
    HasVerify,
    HasWorkspace,
    ToolParams,
    schema_field,
)
from sylvan.tools.base.presenters import (
    FilePresenter,
    ImportPresenter,
    ReferencePresenter,
    SectionPresenter,
    SymbolPresenter,
)
from sylvan.tools.base.tool import MeasureMethod, Tool, get_all_tools, get_registry, get_tool

__all__ = [
    "FilePresenter",
    "HasContextLines",
    "HasDepth",
    "HasDirection",
    "HasDocPath",
    "HasFileFilter",
    "HasFilePath",
    "HasFilePaths",
    "HasKindFilter",
    "HasLanguageFilter",
    "HasMaxDepth",
    "HasOptionalFilePath",
    "HasOptionalProjectPath",
    "HasOptionalRepo",
    "HasOptionalSymbol",
    "HasPagination",
    "HasProjectPath",
    "HasQuery",
    "HasRepo",
    "HasSectionId",
    "HasSectionIds",
    "HasSymbol",
    "HasSymbolIds",
    "HasVerify",
    "HasWorkspace",
    "HintBuilder",
    "ImportPresenter",
    "MeasureMethod",
    "ReferencePresenter",
    "SectionPresenter",
    "SymbolPresenter",
    "Tool",
    "ToolMeta",
    "ToolParams",
    "get_all_tools",
    "get_meta",
    "get_registry",
    "get_tool",
    "reset_meta",
    "schema_field",
    "set_meta",
]
